FROM ubuntu:20.04

ARG BINUTILS_VER
ARG GCC_VER

ENV target=mips32-elf
ENV prefix=/opt/n64
ENV PATH=$prefix/bin:$PATH
ENV MAKEOPTS=-j4
ENV TZ=Europe/London

WORKDIR /tmp

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y build-essential bison flex texinfo \
	curl wget libgmp-dev libmpfr-dev libmpc-dev libisl-dev libzstd-dev xz-utils file && \
	rm -rf /var/lib/apt/lists/*

COPY res/binutils-${BINUTILS_VER}.tar.xz binutils-${BINUTILS_VER}.tar.xz
RUN xz -d binutils-${BINUTILS_VER}.tar.xz && tar xf binutils-${BINUTILS_VER}.tar && \
	mkdir build-binutils && cd build-binutils && \
	../binutils-${BINUTILS_VER}/configure \
		--target=${target} --prefix=${prefix} \
		--program-prefix=${target}- --with-cpu=vr4300 \
		--with-sysroot --disable-nls --disable-werror && \
	make && \
	make install && \
	make clean && rm -rf ./*

COPY res/gcc-${GCC_VER}.tar.xz gcc-${GCC_VER}.tar.xz
RUN xz -d gcc-${GCC_VER}.tar.xz && tar xf gcc-${GCC_VER}.tar && \
	mkdir build-gcc && cd build-gcc && \
	../gcc-${GCC_VER}/configure \
		--target=${target} --prefix=${prefix} \
		--program-prefix=${target}- --with-arch=vr4300 \
		--with-languages=c,c++ --disable-threads \
		--disable-nls --without-headers --with-newlib && \
	make all-gcc && \
	make all-target-libgcc && \
	make install-gcc && \
	make install-target-libgcc && \
	make clean && rm -rf ./*